# Dependencies
markdown:         redcarpet
highlighter:      pygments
redcarpet:
    extensions: [with_toc_data]

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ya.cpp
tagline:          'Yet another C++ code style.'
description:      'Yet another C++ code style.'
url:              http://yacpp.kasoki.de
baseurl:          /

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/kasoki/ya.cpp
